version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./coverage/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      # run:
      #   name: Run linter
      #   command: yarn lint
      - run:
          name: Run tests
          command: yarn circleci
      - store_test_results:
          path: ./coverage/
      # - run:
      #    name: Run built
      #    command: 
workflows:
  build-and-test:
    jobs:
      - test-node
